### ISSUE TITLE
UserNotice is missing from event_map

### ISSUE THREAD

**Issue by JohnPeel** [museun/twitchchat#103]
https://github.com/museun/twitchchat/blob/679e5ea73b90699c3b2b03907cf4339504763160/src/events.rs#L228-L255

Also, this unwrap should have a better error message.
https://github.com/museun/twitchchat/blob/679e5ea73b90699c3b2b03907cf4339504763160/src/runner/dispatcher.rs#L271

**Comment by museun** [comment]
Thanks, I had missed it while refactoring.

The unwrap should never be hit. Only the internal code (that add_event chain) can add events which should be 1:1 with what is in the 'static' map.

I added it (and some other minor methods to message types) in 0.9.3.
