### ISSUE TITLE
Add target matrix for non intel platforms

### ISSUE THREAD

**Issue by museun** [museun/twitchchat#118]
See https://github.com/actions-rs/cargo#cross-compilation

**Comment by Chronophylos** [comment]
I played a bit around with this and I have a working workflow. But it turns out the docker image that `cross` uses has no OpenSSL installed.

The easiest way would be to patch the docker image provided by `cross`: https://github.com/rust-embedded/cross/blob/master/docker/common.sh.
The other way is to create custom docker images, push them to docker hub and use a `cross.toml` to configure the custom image.

**Comment by museun** [comment]
Yeah, OpenSSL on ARMv{6,7} is a pain which is why I added support for `rustls`. 

I think a prelim. approach would be to test it without the native-tls feature enabled and then figure out cross/docker to add in the openssl headers and build them ahead of time.

**Comment by Chronophylos** [comment]
What targets do you want to test against? I'd use Tier 1 from https://forge.rust-lang.org/release/platform-support.html and some from Tier 2.

And what about stable, nightly and beta?

**Comment by museun** [comment]
Stable is fine, if it compiles on stable it should compile on beta/nightly. I develop it against stable.

I should add a MSRP (Minimum supported Rust version). Its somewhere around 1.39 or 1.40 going from memory of from what I use. (async/await is the hard minimum which is 1.39.

As for the Tiers, we'd need to have multiple CI jobs that run on different merge types. A simple dev->master (what I normally do) would be painfully annoying if it tested /every/ platform. Right now just testing on the big 3 for amd64 (win64-msvc, linux-amd64 and macos-amd64) takes almost 5 minutes to run all of the tests.

Some of the 'test' matrix could be reduced. Currently it does some permutation testing of features that are redundant. I don't have the list off the top of my head. But --no-default-features, --all-features, [--features = tokio, tokio+rustls, tokio+native_tls] should be enough until I add support for different async runtimes.

**Comment by museun** [comment]
Added in #132
