### ISSUE TITLE
Listen to multiple channels in twitchchat?

### ISSUE THREAD

**Issue by kingbri1** [museun/twitchchat#174]
I'm not sure if this is a feature already, but other libs such as tmi.js allow for the listening of multiple channels.

For example, I connect as bot account a, but I can listen to channels a and b

How would I accomplish this?

**Comment by museun** [comment]
you would join whatever channels you fancy. https://docs.rs/twitchchat/0.11.8/twitchchat/encode/struct.AsyncEncoder.html#method.join

And with the upcoming code. you would do something along the lines of
```rust
let cmd = join("museun");
writer.encode(cmd).await;
```

**Comment by Emilgardis** [comment]
As mentioned, you can join any channels you want. Just send more joins.

For example, add another join here:
https://github.com/museun/twitchchat/blob/v0.11.8/examples/simple_bot.rs#L49

**Comment by kingbri1** [comment]
Closing this because my question has been answered. Thanks!
