### ISSUE TITLE
support adding tags to commands

### ISSUE THREAD

**Issue by Emilgardis** [museun/twitchchat#180]
Twitch allows it, so this crate should have it.

This is primarily intended to be used for adding `@reply-parent-msg-id=` to `PRIVMSG` to enable the new trial feature of replies.

**Comment by Emilgardis** [comment]
Example bytes sent to irc server:

```text
@reply-parent-msg-id=33230a9e-8855-45ff-88a8-667d57a95b1a PRIVMSG #jtv :this is a reply to a message
```

**Comment by museun** [comment]
This could be part of #99 

I've been thinking about designs for a builder for messages.

**Comment by museun** [comment]
I think, for now, a simple `reply()` vs `privmsg()` could be made.

`reply()` would be something like `reply(channel, to, msg)`

**Comment by Emilgardis** [comment]
The feature is not stable yet, perhaps it's better to wait to implement it and for users to use `Encodable` or use raw command in the mean time.
