### ISSUE TITLE
Unable to compare `BadgeKind`

### ISSUE THREAD

**Issue by jens1o** [museun/twitchchat#2]
Although you are able to access a badge of a user, you may not compare its kind to another, because only `Badge` but not `BadgeKind` is reexported here: https://github.com/museun/twitchchat/blob/028da364865e9a1e1a391dfa00fbc9193f6c8c80/src/twitch/mod.rs#L5

**Comment by museun** [comment]
Thanks, I'm sure there are other re-export problems, just simple oversights.

This will be in 0.1.7

**Comment by jens1o** [comment]
Thanks! :)
