### ISSUE TITLE
Issues when whispering to a user

### ISSUE THREAD

**Issue by kingbri1** [museun/twitchchat#200]
I'm currently trying to make a list subcommand and it's aimed to whisper lines to someone's messages.

My bot account is verified and is able to send whispers and was able to do so in v0.11

However, in 0.13.x, the whisper will not pop up on twitch yet the function was executed

Here's my code: [https://del.dog/ykezucexun.txt](https://del.dog/ykezucexun.txt)

**Comment by museun** [comment]
`whisper()` doesn't actually write anything, it builds a message you can use to  "encode".

```rust
let w = whisper(msg.name(), "---------------------------------------");
writer.encode(&w).await?;

// or
writer.encode_many(&[
    whisper("name", "foo"),
    whisper("name", "bar"),
    whisper("name", "baaz"),
]).await?;
```

**Comment by kingbri1** [comment]
Worked perfectly. Closing this issue.
