### ISSUE TITLE
Privmsg::is_vip() incorrectly returns if the user is the broadcaster.

### ISSUE THREAD

**Issue by DarkRTA** [museun/twitchchat#232]
https://github.com/museun/twitchchat/blob/6d41348ad3b9c7fe7dba489e805f31afec57957f/src/messages/privmsg.rs#L177

The line i linked is incorrect.

I'd open a pr myself but im not at my PC rn.

**Comment by museun** [comment]
Thanks, indeed that is incorrect. It should be `BadgeKind::VIP`: https://github.com/museun/twitchchat/blob/6d41348ad3b9c7fe7dba489e805f31afec57957f/src/twitch/badge.rs#L30
