### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by museun** [museun/twitchchat#67]
Currently this is licensed with the 0-clause BSD license (`0BSD`).

The vastly majority of the Rust ecosystem is dual licensed under `MIT or APACHE`.

I would like to also change this to using those two for `0.8.0`.

If anyone has any qualms (morally, ethically, whatever) about this, I would like to know.

**Comment by Emilgardis** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option

**Comment by museun** [comment]
Its been done. Closing this.
