### ISSUE TITLE
tests.rs files having twitch channel statically set

### ISSUE THREAD

**Issue by Apurer** [museun/twitchchat#88]
Maybe change to environment variables?

- [ ] [decode](https://github.com/museun/twitchchat/blob/master/src/decode/tests.rs)
- [ ] [encode](https://github.com/museun/twitchchat/tree/master/src/encode)
- [ ] [messages](https://github.com/museun/twitchchat/blob/master/src/messages/tests.rs)

**Comment by museun** [comment]
Does this actually cause a problem? Its not a semantic string when parsing. I just grabbed the raw output from my irc client for gathering test data, but if its the anonymizing aspect that you want to achieve then I can just do `#__test_channel` or some other equally invalid twitch channel name. 

If I were to change it, then I guess I could define a bunch of test constants (user, channel, tags, etc). But I don't see whats to be gained by these changes.

**Comment by Apurer** [comment]
I based it on changes within [demo.rs](https://github.com/museun/twitchchat/blob/master/examples/demo.rs) comment:
> // putting this in the env so people don't join my channel when running this

Thought it would be useful to test on different channels.

**Comment by Apurer** [comment]
I was expecting these tests to communicate with twitch irc while testing but none of these do.
